### ISSUE TITLE
hey I cloned the repo but the issue is below 

### ISSUE THREAD

**Issue by asadbukh** [ffmpegwasm/react-app#11]
ffmpeg-core.js is loading and never executes..
# its happening from. 30 minutes 
i restarted several times but issue is same

![Screen Shot 2022-02-28 at 1 57 15 PM](https://user-images.githubusercontent.com/89916773/155953739-22c31674-2c26-4c2a-905f-404403c2ea39.png)
.

**Comment by nikepick** [comment]
1. clone repo
2. run "yarn install"
3. run "yarn start"

I have no idea why it is not working with npm, I tried making the entire thing with npm commands and I am unable to load ffmpeg

**Comment by Marshal1101** [comment]
it must be the error

Uncaught (in promise) ReferenceError: SharedArrayBuffer is not defined
    at ffmpeg-core.js:22:175
    at Object.load (createFFmpeg.js:54:1)
    at async doTranscode (App.js:14:1)

how can I fix this error...

**Comment by nikepick** [comment]
create **setupProxy.js** in root of the project and add the following lines to it:

```
module.exports = function (app) {
    app.use(function (req, res, next) {
        res.setHeader("Cross-Origin-Opener-Policy", "same-origin");
        res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");
        next();
    });
};
```

**Comment by zheoreh** [comment]
@nikepick I've added setupProxy.js but I still have the issue with SharedArrayBuffer
